services: 

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database
    volumes:
      # - ./backend:/app/backend
      # - ./app/backend/node_modules:/app/backend/node_modules
      - ./data:/var/opt/mssql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=Naranja90*
      - ACCEPT_EULA=Y
    networks:
      - red
    restart: always

networks:
  red:
    external: true