
module.exports = (sequelize, DataTypes) => {
    const Model = sequelize.define(
        "Clientes",
        {
            NUMERO:  {
                type: DataTypes.STRING,
                primaryKey: true
            }, 
            RAZONSOC: DataTypes.STRING, 
            DIRECCION: DataTypes.STRING, 
            LOCALIDAD: DataTypes.STRING, 
            CODPOSTAL: DataTypes.STRING, 
            PROVINCIA: DataTypes.STRING, 
            PAIS: DataTypes.STRING, 
            IMPUESTO: DataTypes.STRING, 
            CUIT: DataTypes.STRING, 
            IGRBRT: DataTypes.STRING, 
            TELEFONOS: DataTypes.STRING, 
            DESCUENTO: DataTypes.FLOAT, 
            DESCUENTOESP: DataTypes.FLOAT, 
            BONIFADTO: DataTypes.STRING,
            CODFACT: DataTypes.STRING, 
            CONDVTA: DataTypes.STRING, 
            CONDVTAFIJA: DataTypes.STRING, 
            FECULTVTA: DataTypes.DATE, 
            IMPUTACML: DataTypes.STRING, 
            IMPUTACME: DataTypes.STRING, 
            AGRUPA: DataTypes.STRING, 
            DOMENTREGA: DataTypes.STRING, 
            CONTACTO: DataTypes.STRING,
            COBRANZAS: DataTypes.STRING, 
            FECCREDITO: DataTypes.DATE, 
            IMPCREDITO: DataTypes.FLOAT, 
            VENDEDOR: DataTypes.STRING, 
            FECINHAB: DataTypes.DATE, 
            LISTAPREC: DataTypes.STRING, 
            LISTAFIJA: DataTypes.STRING,
            MONEMISION: DataTypes.STRING, 
            COPIASFACT: DataTypes.STRING, 
            COPIASREM: DataTypes.STRING, 
            CCOSTOSML: DataTypes.STRING, 
            CCOSTOSME: DataTypes.STRING, 
            COBRADOR: DataTypes.STRING, 
            IVALIBERAD: DataTypes.FLOAT, 
            GENERAEST: DataTypes.STRING, 
            FACTURABLE: DataTypes.STRING, 
            CODIGOCUIT: DataTypes.STRING, 
            NUMCTACTE: DataTypes.STRING, 
            AUXILIAR1: DataTypes.STRING, 
            AUXILIAR2: DataTypes.STRING, 
            AUXILIAR3: DataTypes.STRING, 
            AUXILIAR4: DataTypes.STRING, 
            EMAIL: DataTypes.STRING, 
            WEB: DataTypes.STRING, 
            FECALTA: DataTypes.DATE, 
            USUARIO: DataTypes.STRING, 
            FECMOD: DataTypes.STRING, 
            USRMOD: DataTypes.STRING, 
            CUENTA: DataTypes.STRING, 
            GENERAFC: DataTypes.STRING, 
            AGENTERET: DataTypes.STRING,
            DIFCAMBIO: DataTypes.STRING, 
            PERCEPIVA: DataTypes.FLOAT, 
            FECVTOIVA: DataTypes.DATE, 
            ANEGOCIOML: DataTypes.STRING, 
            ANEGOCIOME: DataTypes.STRING, 
            IMPUTACRML: DataTypes.STRING, 
            IMPUTACRME: DataTypes.STRING, 
            CCOSTOSRML: DataTypes.STRING, 
            CCOSTOSRME: DataTypes.STRING, 
            ANEGOCIORML: DataTypes.STRING, 
            ANEGOCIORME: DataTypes.STRING, 
            CALCPIBPR: DataTypes.STRING, 
            FECPROXLLAM: DataTypes.DATE, 
            FECCOBRANZA: DataTypes.DATE, 
            COBASIGNADO: DataTypes.STRING, 
            LUGARCOB: DataTypes.STRING, 
            LLAMADOS: DataTypes.STRING, 
            CONFENT: DataTypes.STRING, 
            CODOTRSIS: DataTypes.STRING, 
            CATEGORIA: DataTypes.STRING, 
            CLAVEPERSONAL: DataTypes.STRING, 
            CODPAIS: DataTypes.STRING,
            TIPOEXPORTACION: DataTypes.STRING, 
            IDIOMACOMP: DataTypes.STRING, 
            MONEDAEXPORTACION: DataTypes.STRING,
            INCOTERMS: DataTypes.STRING, 
            IDTRIBUTARIA1: DataTypes.STRING, 
            IDTRIBUTARIA2: DataTypes.STRING, 
            FECVALCON: DataTypes.DATE, 
            ESTADOCI: DataTypes.STRING, 
            VINCULADO: DataTypes.STRING, 
            COBASIGNO: DataTypes.STRING, 
            FECCOBALTA: DataTypes.DATE, 
            VIAEXPORTACION: DataTypes.STRING, 
            FANTASIA: DataTypes.STRING, 
            FECPROXLLAMSC: DataTypes.DATE, 
            USUARIOSC: DataTypes.STRING, 
            AUTORIZARFACTURA: DataTypes.STRING, 
            AUTORIZARIMPAGAS: DataTypes.STRING, 
            AUTORIZARDESCUENTOS: DataTypes.STRING, 
            GLN: DataTypes.STRING,

        },
        {
            tableName: "clientes",
            timestamps: false,   
        }
    );

    Model.associate = (models) => {
        // Model.hasMany(models.Pedidos, {
        //     as: 'pedidos',
        //     foreignKey: 'CLIENTE',
        // });
 
        // Model.belongsTo(models.Categorias, {
        //     as: 'categorias',
        //     foreignKey: 'categoria_id',
        // });
    };

    return Model;
}