  
services: 

  backend:
    build:
      context: ../../backend
    container_name: backend
    ports:
      - "3000:3000"
    # volumes:
    #   - ../../backend:/app
    networks:
      - red
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_DIALECT=${DB_DIALECT}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.mi-proyecto.local`)"
      - "traefik.http.services.backend-service.loadbalancer.server.port=3000"
  
  frontend:
    build:
      context: ../../frontend
    container_name: frontend
    ports:
      - "3001:3001"
    volumes:
      - ../../frontend:/app
    networks:
      - red
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.mi-proyecto.local`)"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=3001"

networks:
  red:
    external: true
